services:
  PrestaShop\Module\PsEventbus\Adapter\ConfigurationAdapter:
    class: PrestaShop\Module\PsEventbus\Adapter\ConfigurationAdapter
    arguments:
      - '@=service("ps_eventbus.shop").id'

  PrestaShop\Module\PsEventbus\Adapter\ToolsAdapter:
    class: PrestaShop\Module\PsEventbus\Adapter\ToolsAdapter
