services:
  PrestaShop\Module\PsEventbus\Api\SyncApiClient:
    class: PrestaShop\Module\PsEventbus\Api\SyncApiClient
    arguments:
      - '%ps_eventbus.sync_api_url%'
      - '@ps_eventbus'
      - '@PrestaShop\Module\PsEventbus\Service\PsAccountsAdapterService'

  PrestaShop\Module\PsEventbus\Api\LiveSyncApiClient:
    class: PrestaShop\Module\PsEventbus\Api\LiveSyncApiClient
    arguments:
      - '%ps_eventbus.live_sync_api_url%'
      - '@ps_eventbus'
      - '@PrestaShop\Module\PsEventbus\Service\PsAccountsAdapterService'

  PrestaShop\Module\PsEventbus\Api\CollectorApiClient:
    class: PrestaShop\Module\PsEventbus\Api\CollectorApiClient
    arguments:
      - '%ps_eventbus.proxy_api_url%'
      - '@ps_eventbus'
      - '@PrestaShop\Module\PsEventbus\Service\PsAccountsAdapterService'
