services:
  PrestaShop\Module\PsEventbus\Api\SyncApiClient:
    class: PrestaShop\Module\PsEventbus\Api\SyncApiClient
    public: true
    arguments:
      - '@PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
      - "%ps_eventbus.sync_api_url%"
      - "@ps_eventbus"

  PrestaShop\Module\PsEventbus\Api\CollectorApiClient:
    class: PrestaShop\Module\PsEventbus\Api\CollectorApiClient
    public: true
    arguments:
      - '@PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
      - "%ps_eventbus.proxy_api_url%"
      - "@ps_eventbus"
