services:
  PrestaShop\Module\PsEventbus\Api\EventBusSyncClient:
    class: PrestaShop\Module\PsEventbus\Api\EventBusSyncClient
    arguments:
      - '@ps_eventbus.link'
      - '@PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
      - '%ps_eventbus.sync_api_url%'

  PrestaShop\Module\PsEventbus\Api\EventBusProxyClient:
    class: PrestaShop\Module\PsEventbus\Api\EventBusProxyClient
    arguments:
      - '@ps_eventbus.link'
      - '@PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
      - '%ps_eventbus.proxy_api_url%'
