parameters:
  ps_eventbus.proxy_api_url: "http://reverse-proxy/collector"
  ps_eventbus.sync_api_url: "http://reverse-proxy/sync-api"
  ps_eventbus.live_sync_api_url: "http://reverse-proxy/live-sync-api/v1"
  ps_eventbus.sentry_dsn: "https://457f191226df4b8f9a0d7bf6f250bab2@o298402.ingest.sentry.io/6066714"
  ps_eventbus.sentry_env: "integration"
