version: "3"

services:
    php:
        image: phpdockerio/php72-cli
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        environment:
            _PS_ROOT_DIR_: /var/www/html
    node:
        image: node:lts-alpine
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        environment:
            PATH: /var/www/html/_dev/node_modules/.bin/:$PATH

    mysql:
        container_name: sq-mysql
        image: mysql:5.7
        ports:
            - "9001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: prestashop
            MYSQL_DATABASE: prestashop
        restart: unless-stopped
        healthcheck:
            test: "mysqladmin ping -h127.0.0.1 -uroot -pprestashop --silent"
            interval: 10s

    prestashop-177:
        container_name: prestashop-177
        build:
            context: .
            dockerfile: .docker/Dockerfile
        environment:
            PS_INSTALL_AUTO: 0
            DB_PASSWD: prestashop
            DB_NAME: prestashop
            DB_SERVER: mysql
            PS_DOMAIN: 172.17.0.1:8001
            PS_FOLDER_INSTALL: install
            PS_FOLDER_ADMIN: admin1
        depends_on:
            - mysql
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www/html/modules/ps_eventbus
            - ./tests/System/Seed/Config/defines.inc.php:/var/www/html/config/defines.inc.php
            - ./tests/System/Seed/Config/parameters.php:/var/www/html/app/config/parameters.php
            - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        healthcheck:
            test: "wget --no-verbose --tries=1 --spider http://localhost:80 || exit 1"
            interval: 10s
