imports:
  - { resource: ../parameters.yml }

services:
  ps_eventbus.db:
    class: Db
    factory: ['Db', 'getInstance']

  ps_eventbus:
    class: 'Ps_eventbus'
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'ps_eventbus'
  
  ps_eventbus.context:
    class: 'Context'
    factory: ['PrestaShop\Module\PsEventbus\Factory\ContextFactory', 'getContext']

  ps_eventbus.helper.module:
    class: 'PrestaShop\Module\PsEventbus\Helper\ModuleHelper'

  PrestaShop\Module\PsEventbus\Service\PsAccountsAdapterService:
    class: PrestaShop\Module\PsEventbus\Service\PsAccountsAdapterService
    arguments: 
      - '@ps_eventbus.helper.module'

  PrestaShop\Module\PsEventbus\Formatter\JsonFormatter:
    class: PrestaShop\Module\PsEventbus\Formatter\JsonFormatter

  PrestaShop\Module\PsEventbus\Formatter\ArrayFormatter:
    class: PrestaShop\Module\PsEventbus\Formatter\ArrayFormatter

  PrestaShop\Module\PsEventbus\Service\ProxyService:
    class: PrestaShop\Module\PsEventbus\Service\ProxyService
    arguments:
      - '@PrestaShop\Module\PsEventbus\Api\CollectorApiClient'
      - '@PrestaShop\Module\PsEventbus\Formatter\JsonFormatter'
      - '@PrestaShop\Module\PsEventbus\Handler\ErrorHandler\ErrorHandlerInterface'

  PrestaShop\Module\PsEventbus\Handler\ErrorHandler\ErrorHandlerInterface: '@PrestaShop\Module\PsEventbus\Handler\ErrorHandler\ErrorHandler'

  PrestaShop\Module\PsEventbus\Handler\ErrorHandler\ErrorHandler:
    class: PrestaShop\Module\PsEventbus\Handler\ErrorHandler\ErrorHandler
    arguments:
      - '@ps_eventbus'
      - '@PrestaShop\Module\PsEventbus\Service\PsAccountsAdapterService'
      - '%ps_eventbus.sentry_dsn%'
      - '%ps_eventbus.sentry_env%'
