services:
  PrestaShop\Module\PsEventbus\Decorator\CategoryDecorator:
    class: PrestaShop\Module\PsEventbus\Decorator\CategoryDecorator

  PrestaShop\Module\PsEventbus\Decorator\CurrencyDecorator:
    class: PrestaShop\Module\PsEventbus\Decorator\CurrencyDecorator

  PrestaShop\Module\PsEventbus\Decorator\CustomerDecorator:
    class: PrestaShop\Module\PsEventbus\Decorator\CustomerDecorator

  PrestaShop\Module\PsEventbus\Decorator\PayloadDecorator:
    class: PrestaShop\Module\PsEventbus\Decorator\PayloadDecorator
    arguments:
      - '@PrestaShop\Module\PsEventbus\Repository\ConfigurationRepository'

  PrestaShop\Module\PsEventbus\Decorator\CustomPriceDecorator:
    class: PrestaShop\Module\PsEventbus\Decorator\CustomPriceDecorator
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'
      - '@PrestaShop\Module\PsEventbus\Service\SpecificPriceService'

  PrestaShop\Module\PsEventbus\Decorator\WishlistDecorator:
    class: PrestaShop\Module\PsEventbus\Decorator\WishlistDecorator

  PrestaShop\Module\PsEventbus\Decorator\StoreDecorator:
    class: PrestaShop\Module\PsEventbus\Decorator\StoreDecorator

  PrestaShop\Module\PsEventbus\Decorator\StockDecorator:
    class: PrestaShop\Module\PsEventbus\Decorator\StockDecorator

  PrestaShop\Module\PsEventbus\Decorator\ManufacturerDecorator:
    class: PrestaShop\Module\PsEventbus\Decorator\ManufacturerDecorator

  PrestaShop\Module\PsEventbus\Decorator\SupplierDecorator:
    class: PrestaShop\Module\PsEventbus\Decorator\SupplierDecorator

  PrestaShop\Module\PsEventbus\Decorator\ProductSupplierDecorator:
    class: PrestaShop\Module\PsEventbus\Decorator\ProductSupplierDecorator

  PrestaShop\Module\PsEventbus\Decorator\EmployeeDecorator:
    class: PrestaShop\Module\PsEventbus\Decorator\EmployeeDecorator

  PrestaShop\Module\PsEventbus\Decorator\LanguageDecorator:
    class: PrestaShop\Module\PsEventbus\Decorator\LanguageDecorator

  PrestaShop\Module\PsEventbus\Decorator\ImageDecorator:
    class: PrestaShop\Module\PsEventbus\Decorator\ImageDecorator

  PrestaShop\Module\PsEventbus\Decorator\ImageTypeDecorator:
    class: PrestaShop\Module\PsEventbus\Decorator\ImageTypeDecorator

  PrestaShop\Module\PsEventbus\Decorator\TranslationDecorator:
    class: PrestaShop\Module\PsEventbus\Decorator\TranslationDecorator
