services:
  PrestaShop\Module\PsEventbus\Decorator\PayloadDecorator:
    class: PrestaShop\Module\PsEventbus\Decorator\PayloadDecorator
    public: true

  PrestaShop\Module\PsEventbus\Decorator\StoreDecorator:
    class: PrestaShop\Module\PsEventbus\Decorator\StoreDecorator
    public: true

  PrestaShop\Module\PsEventbus\Decorator\SupplierDecorator:
    class: PrestaShop\Module\PsEventbus\Decorator\SupplierDecorator
    public: true
