services:
  PrestaShop\Module\PsEventbus\Repository\NewRepository\OrderRepository:
    class: PrestaShop\Module\PsEventbus\Repository\NewRepository\OrderRepository

  PrestaShop\Module\PsEventbus\Repository\NewRepository\OrderCartRuleRepository:
    class: PrestaShop\Module\PsEventbus\Repository\NewRepository\OrderCartRuleRepository
  
  PrestaShop\Module\PsEventbus\Repository\NewRepository\OrderHistoryRepository:
    class: PrestaShop\Module\PsEventbus\Repository\NewRepository\OrderHistoryRepository

  PrestaShop\Module\PsEventbus\Repository\NewRepository\OrderDetailRepository:
    class: PrestaShop\Module\PsEventbus\Repository\NewRepository\OrderDetailRepository

  PrestaShop\Module\PsEventbus\Repository\NewRepository\CarrierRepository:
    class: PrestaShop\Module\PsEventbus\Repository\NewRepository\CarrierRepository

  PrestaShop\Module\PsEventbus\Repository\NewRepository\CartRepository:
    class: PrestaShop\Module\PsEventbus\Repository\NewRepository\CartRepository

  PrestaShop\Module\PsEventbus\Repository\NewRepository\CartProductRepository:
    class: PrestaShop\Module\PsEventbus\Repository\NewRepository\CartProductRepository

  PrestaShop\Module\PsEventbus\Repository\NewRepository\CartRuleRepository:
    class: PrestaShop\Module\PsEventbus\Repository\NewRepository\CartRuleRepository

  PrestaShop\Module\PsEventbus\Repository\NewRepository\ProductRepository:
    class: PrestaShop\Module\PsEventbus\Repository\NewRepository\ProductRepository

  PrestaShop\Module\PsEventbus\Repository\NewRepository\ProductBundleRepository:
    class: PrestaShop\Module\PsEventbus\Repository\NewRepository\ProductBundleRepository

  PrestaShop\Module\PsEventbus\Repository\NewRepository\ProductSupplierRepository:
    class: PrestaShop\Module\PsEventbus\Repository\NewRepository\ProductSupplierRepository

  PrestaShop\Module\PsEventbus\Repository\NewRepository\ProductCarrierRepository:
    class: PrestaShop\Module\PsEventbus\Repository\NewRepository\ProductCarrierRepository

  PrestaShop\Module\PsEventbus\Repository\NewRepository\CategoryRepository:
    class: PrestaShop\Module\PsEventbus\Repository\NewRepository\CategoryRepository
  
  PrestaShop\Module\PsEventbus\Repository\NewRepository\CustomerRepository:
    class: PrestaShop\Module\PsEventbus\Repository\NewRepository\CustomerRepository

  PrestaShop\Module\PsEventbus\Repository\NewRepository\CurrencyRepository:
    class: PrestaShop\Module\PsEventbus\Repository\NewRepository\CurrencyRepository

  PrestaShop\Module\PsEventbus\Repository\NewRepository\EmployeeRepository:
    class: PrestaShop\Module\PsEventbus\Repository\NewRepository\EmployeeRepository
