services:
  PrestaShop\Module\PsEventbus\Repository\ConfigurationRepository:
    class: PrestaShop\Module\PsEventbus\Repository\ConfigurationRepository
    public: true

  PrestaShop\Module\PsEventbus\Repository\EventbusSyncRepository:
    class: PrestaShop\Module\PsEventbus\Repository\EventbusSyncRepository
    public: true
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'

  PrestaShop\Module\PsEventbus\Repository\IncrementalSyncRepository:
    class: PrestaShop\Module\PsEventbus\Repository\IncrementalSyncRepository
    public: true
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'
      - '@PrestaShop\Module\PsEventbus\Handler\ErrorHandler\ErrorHandlerInterface'

  PrestaShop\Module\PsEventbus\Repository\ShopRepository:
    class: PrestaShop\Module\PsEventbus\Repository\ShopRepository
    public: true

  PrestaShop\Module\PsEventbus\Repository\CountryRepository:
    class: PrestaShop\Module\PsEventbus\Repository\CountryRepository
    public: true
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'

  PrestaShop\Module\PsEventbus\Repository\StateRepository:
    class: PrestaShop\Module\PsEventbus\Repository\StateRepository
    public: true

  PrestaShop\Module\PsEventbus\Repository\TaxeRepository:
    class: PrestaShop\Module\PsEventbus\Repository\TaxeRepository
    public: true
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'
  
  PrestaShop\Module\PsEventbus\Repository\LiveSyncRepository:
    class: PrestaShop\Module\PsEventbus\Repository\LiveSyncRepository
    public: true
