services:
  PrestaShop\Module\PsEventbus\Repository\LanguageRepository:
    class: PrestaShop\Module\PsEventbus\Repository\LanguageRepository
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'

  PrestaShop\Module\PsEventbus\Repository\ConfigurationRepository:
    class: PrestaShop\Module\PsEventbus\Repository\ConfigurationRepository

  PrestaShop\Module\PsEventbus\Repository\EventbusSyncRepository:
    class: PrestaShop\Module\PsEventbus\Repository\EventbusSyncRepository
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'

  PrestaShop\Module\PsEventbus\Repository\ModuleRepository:
    class: PrestaShop\Module\PsEventbus\Repository\ModuleRepository

  PrestaShop\Module\PsEventbus\Repository\ServerInformationRepository:
    class: PrestaShop\Module\PsEventbus\Repository\ServerInformationRepository
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'
      - '@PrestaShop\Module\PsEventbus\Service\PsAccountsAdapterService'
      - '@PrestaShop\Module\PsEventbus\Repository\LanguageRepository'
      - '@PrestaShop\Module\PsEventbus\Repository\ConfigurationRepository'
      - '@PrestaShop\Module\PsEventbus\Repository\ShopRepository'
      - '@PrestaShop\Module\PsEventbus\Service\ShopContent\CurrenciesService'
      - '@PrestaShop\Module\PsEventbus\Handler\ErrorHandler\ErrorHandlerInterface'
      - '%ps_eventbus.sync_api_url%'
      - '%ps_eventbus.live_sync_api_url%'
      - '%ps_eventbus.proxy_api_url%'

  PrestaShop\Module\PsEventbus\Repository\ThemeRepository:
    class: PrestaShop\Module\PsEventbus\Repository\ThemeRepository
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'

  PrestaShop\Module\PsEventbus\Repository\GoogleTaxonomyRepository:
    class: PrestaShop\Module\PsEventbus\Repository\GoogleTaxonomyRepository

  PrestaShop\Module\PsEventbus\Repository\IncrementalSyncRepository:
    class: PrestaShop\Module\PsEventbus\Repository\IncrementalSyncRepository
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'
      - '@PrestaShop\Module\PsEventbus\Handler\ErrorHandler\ErrorHandlerInterface'

  PrestaShop\Module\PsEventbus\Repository\ShopRepository:
    class: PrestaShop\Module\PsEventbus\Repository\ShopRepository

  PrestaShop\Module\PsEventbus\Repository\CountryRepository:
    class: PrestaShop\Module\PsEventbus\Repository\CountryRepository
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'

  PrestaShop\Module\PsEventbus\Repository\StateRepository:
    class: PrestaShop\Module\PsEventbus\Repository\StateRepository

  PrestaShop\Module\PsEventbus\Repository\TaxeRepository:
    class: PrestaShop\Module\PsEventbus\Repository\TaxeRepository
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'

  PrestaShop\Module\PsEventbus\Repository\CustomPriceRepository:
    class: PrestaShop\Module\PsEventbus\Repository\CustomPriceRepository
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'

  PrestaShop\Module\PsEventbus\Repository\WishlistRepository:
    class: PrestaShop\Module\PsEventbus\Repository\WishlistRepository
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'

  PrestaShop\Module\PsEventbus\Repository\WishlistProductRepository:
    class: PrestaShop\Module\PsEventbus\Repository\WishlistProductRepository

  PrestaShop\Module\PsEventbus\Repository\SpecificPriceRepository:
    class: PrestaShop\Module\PsEventbus\Repository\SpecificPriceRepository

  PrestaShop\Module\PsEventbus\Repository\StoreRepository:
    class: PrestaShop\Module\PsEventbus\Repository\StoreRepository
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'

  PrestaShop\Module\PsEventbus\Repository\StockRepository:
    class: PrestaShop\Module\PsEventbus\Repository\StockRepository
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'

  PrestaShop\Module\PsEventbus\Repository\StockMvtRepository:
    class: PrestaShop\Module\PsEventbus\Repository\StockMvtRepository

  PrestaShop\Module\PsEventbus\Repository\ManufacturerRepository:
    class: PrestaShop\Module\PsEventbus\Repository\ManufacturerRepository
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'

  PrestaShop\Module\PsEventbus\Repository\SupplierRepository:
    class: PrestaShop\Module\PsEventbus\Repository\SupplierRepository
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'
  
  PrestaShop\Module\PsEventbus\Repository\ImageRepository:
    class: PrestaShop\Module\PsEventbus\Repository\ImageRepository

  PrestaShop\Module\PsEventbus\Repository\ImageTypeRepository:
    class: PrestaShop\Module\PsEventbus\Repository\ImageTypeRepository
  
  PrestaShop\Module\PsEventbus\Repository\TranslationRepository:
    class: PrestaShop\Module\PsEventbus\Repository\TranslationRepository
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'
      
  PrestaShop\Module\PsEventbus\Repository\LiveSyncRepository:
    class: PrestaShop\Module\PsEventbus\Repository\LiveSyncRepository
