---
root: true
env:
  jest: true
  es6: true
plugins:
  - '@typescript-eslint'
  - deprecation
  - import
  - unicorn
  - prettier
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  project: true
ignorePatterns:
  - 'dist/'
  - 'node_modules/'
  - 'coverage/'
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - '.ts'
  import/resolver:
    typescript:
      project: true
    node:
      project: true
rules:
  'prettier/prettier': error
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  unicorn/filename-case:
    - error
    - case: kebabCase
  deprecation/deprecation: warn
  import/no-unresolved: error
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '**/*.ts'
      optionalDependencies:
        - '**/*.ts'
      peerDependencies: true
