---
name: Build staging module

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

env:
  PHP_BUILDER_VERSION: "8.3"
  GITHUB_TOKEN: ${{ secrets.GA_ACCESS_TOKEN }}

jobs:
  build_and_update_staging_release:
    name: Build and publish staging assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_BUILDER_VERSION }}

      - name: Bundle zips
        run: make zip
        env:
          VERSION: staging

      - name: Move the staging tag
        run: |
          git tag -d staging | true
          git tag staging
          git push origin :refs/tags/staging
          git push origin staging

      - name: Update release
        id: update_staging_release
        uses: joutvhu/create-release@v1
        with:
          tag_name: staging
          name: staging
          prerelease: true
          on_release_exists: update
          generate_release_notes: true
          remove_assets: true

      - name: Push the integration zip
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.update_staging_release.outputs.upload_url }}
          asset_path: ./dist/${{ github.event.repository.name }}-staging_integration.zip
          asset_name: ${{ github.event.repository.name }}-staging_integration.zip
          asset_content_type: application/zip

      - name: Push the e2e zip
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.update_staging_release.outputs.upload_url }}
          asset_path: ./dist/${{ github.event.repository.name }}-staging_e2e.zip
          asset_name: ${{ github.event.repository.name }}-staging_e2e.zip
          asset_content_type: application/zip

      - name: Push the production zip
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.update_staging_release.outputs.upload_url }}
          asset_path: ./dist/${{ github.event.repository.name }}-staging.zip
          asset_name: ${{ github.event.repository.name }}-staging.zip
          asset_content_type: application/zip
