---
name: Build staging module

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

env:
  PHP_BUILDER_VERSION: "8.3"

jobs:
  update_staging_release:
    name: Build and update staging assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_BUILDER_VERSION }}

      - name: Bundle zips
        run: make zip

      - name: Update release
        uses: johnwbyrd/update-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: dist/*.zip
          release: staging
