---
name: Bump staging

on:
  push:
    branches:
      - main

jobs:
  bump_staging_tag:
    name: Bump staging and notify to build assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Move the staging tag
        run: |
          git tag -d staging | true
          git tag staging
          git push origin :refs/tags/staging
          git push origin staging

      - name: Notify build workflow
        run: |
          gh release delete staging || true
          gh release create staging \
            --title "🐣 staging (commit $(git rev-parse --short HEAD))" \
            --prerelease \
            --generate-notes \
            --latest=false
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
