name: E2e

on:
  schedule:
    - cron: '1 0 * * *'

env:
  DOCKER_COMPOSE_VERSION: v2.27.0
  NODE_BUILDER_VERSION: "20"

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - ps-version: 8.1.6
            php-version: 8.2
          - ps-version: 8.0.5
            php-version: 8.2
          - ps-version: 1.7.8.11
            php-version: 7.4
          - ps-version: 1.7.7.8
            php-version: 7.3
          - ps-version: 1.7.6.9
            php-version: 7.2
          - ps-version: 1.7.5.2
            php-version: 7.2
          - ps-version: 1.7.4.4
            php-version: 7.1
          - ps-version: 1.7.3.4
            php-version: 7.1
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Auth Docker GCP
        uses: ./.github/actions/auth-docker-gcp
        with:
          workload-identity-provider: ${{ secrets.WI_PROVIDER_INTEGRATION }}
          service-account: ${{ secrets.WI_SA_INTEGRATION }}

      - name: e2e tests
        uses: ./.github/actions/e2e
        with:
          ps-version: ${{ matrix.ps-version }}
          php-version: ${{ matrix.php-version }}
          docker-compose-version: ${{ env.DOCKER_COMPOSE_VERSION }}
          node-builder-version: ${{ env.NODE_BUILDER_VERSION }}

      - name: Slack notification on failures
        if: github.event_name == 'schedule' && failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: EC1111
          SLACK_TITLE: E2E Capture tests PS${{ matrix.ps-version }} & Php${{ matrix.php-version }}
          SLACK_MESSAGE: The latest E2E Capture tests failed :(
          SLACK_FOOTER: 'Review the last github actions here: https://github.com/PrestaShopCorp/cloudsync/actions/workflows/e2e.yml'
          SLACK_USERNAME: QABot
          SLACK_CHANNEL: squad-cloudsync-dev
          SLACK_ICON: https://avatars.githubusercontent.com/u/56089550?s=48&v=4

      - name: Slack notification on success
        if: github.event_name == 'schedule' && success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: 0CAD34
          SLACK_TITLE: E2E Capture tests PS${{ matrix.ps-version }} & Php${{ matrix.php-version }}
          SLACK_MESSAGE: ✓ The latest E2E Capture tests just passed!
          SLACK_FOOTER: ''
          SLACK_USERNAME: QABot
          SLACK_CHANNEL: cloudsync-alerting
          SLACK_ICON: https://avatars.githubusercontent.com/u/56089550?s=48&v=4
