---
name: E2E

on:
  schedule:
    - cron: '1 0 * * *'
  workflow_dispatch:

env:
  DOCKER_COMPOSE_VERSION: v2.24.4
  PNPM_VERSION: 9

jobs:
  # E2E tests are enable, only for:
  # - Scheduled every day at 01:00 am (production)
  e2e-eventbus-tests:
    name: E2E Eventbus Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      fail-fast: false
      matrix:
        campaign: [
          { ps: 8.1.6, php: 8.1 },
          { ps: 8.0.5, php: 8.1 },
          { ps: 1.7.8.11, php: 7.4 },
          { ps: 1.7.7.8, php: 7.3 },
          { ps: 1.7.6.9, php: 7.2 },
          { ps: 1.7.5.2, php: 7.2 },
          { ps: 1.7.4.4, php: 7.1 },
          { ps: 1.7.3.4, php: 7.1 }
        ]
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Auth Docker GCP
        uses: ./.github/actions/auth-docker-gcp
        with:
          workload-identity-provider: ${{ secrets.WI_PROVIDER_INTEGRATION }}
          service-account: ${{ secrets.WI_SA_INTEGRATION }}

      - name: e2e tests
        uses: ./.github/actions/e2e
        with:
          github-event-name: ${{ github.event_name }}
          ps-version: ${{ matrix.campaign.ps }}
          php-version: ${{ matrix.campaign.php }}
          docker-compose-version: ${{ env.DOCKER_COMPOSE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
          npm-token-prestashopcorp: ${{ secrets.NPM_TOKEN_PRESTASHOPCORP }}

      - name: Slack notification on failures
        if: github.event_name == 'schedule' && failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: EC1111
          SLACK_TITLE: E2E Eventbus module tests
          SLACK_MESSAGE: The latest E2E Eventbus module tests failed :(
          SLACK_FOOTER: 'Review the last github actions here: https://github.com/PrestaShopCorp/ps_eventbus/actions/workflows/e2e.yml'
          SLACK_USERNAME: QABot
          SLACK_CHANNEL: squad-cloudsync-dev
          SLACK_ICON: https://avatars.githubusercontent.com/u/56089550?s=48&v=4

      - name: Slack notification on success
        if: github.event_name == 'schedule' && success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: 0CAD34
          SLACK_TITLE: E2E Capture tests
          SLACK_MESSAGE: ✓ The latest E2E Eventbus module tests just passed!
          SLACK_FOOTER: ''
          SLACK_USERNAME: QABot
          SLACK_CHANNEL: cloudsync-alerting
          SLACK_ICON: https://avatars.githubusercontent.com/u/56089550?s=48&v=4
